-- Phase 1.5 — network inventory ledger + dealer ordering (Supabase / Postgres).
-- Authoritative schema: matches the deployed project. Run once in the SQL editor,
-- then run seed.sql (generated by build-seed.mjs).
-- Rules mirror ledger.js: balances DERIVE from movements; RLS IS the visibility tree.

-- ---------- reference data ----------
create table if not exists parties (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  role        text not null check (role in ('importer','distributor','dealer','shopkeeper','enduser')),
  parent_id   uuid references parties(id),          -- null only for the importer (tree root)
  city        text,
  pin         text,
  margin_pct  numeric,                              -- per-party override; null = role default
  auth_uid    uuid unique references auth.users(id),-- linked when the party gets a login
  created_at  timestamptz not null default now()
);
create index if not exists parties_parent_idx on parties(parent_id);

-- public, non-sensitive: names/structure only. NO landing cost here (see catalog_cost).
create table if not exists catalog (
  sku          text primary key,   -- stable per catalog line (build-seed.mjs: L0001, L0002, …)
  grp          int,
  section      text,
  product_code text,
  particular   text,
  pdf_page     int
);

-- landing/cost price lives here, importer-only (RLS below). Never exposed to dealers.
create table if not exists catalog_cost (
  sku         text primary key references catalog(sku),
  dealer_rate numeric
);

-- default markup per tier (from the pilot's accounts.json); parties.margin_pct overrides
create table if not exists role_margins ( role text primary key, margin_pct numeric not null );

-- one row per transfer (double-entry). from_party null = external/opening stock.
create table if not exists movements (
  id          bigint generated always as identity primary key,
  from_party  uuid references parties(id),
  to_party    uuid not null references parties(id),
  sku         text not null references catalog(sku),
  qty         int  not null check (qty > 0),
  pi_number   text,
  note        text,
  created_at  timestamptz not null default now(),
  created_by  uuid default auth.uid()
);
create index if not exists movements_to_idx   on movements(to_party, sku);
create index if not exists movements_from_idx on movements(from_party, sku);

-- current balance = incoming - outgoing, per (party, sku). security_invoker so the
-- view honours the caller's RLS on movements (else it would leak every party's stock).
create or replace view current_stock with (security_invoker = true) as
  select party_id, sku, sum(delta)::int as qty
  from (
    select to_party   as party_id, sku,  qty as delta from movements
    union all
    select from_party as party_id, sku, -qty as delta from movements where from_party is not null
  ) t
  group by party_id, sku
  having sum(delta) <> 0;

-- ---------- tree helpers ----------
create or replace function my_party() returns uuid
  language sql stable security definer set search_path = public as $$
  select id from parties where auth_uid = auth.uid()
$$;

create or replace function subtree(root uuid) returns setof uuid
  language sql stable security definer set search_path = public as $$
  with recursive t as (
    select id from parties where id = root
    union all
    select p.id from parties p join t on p.parent_id = t.id
  ) select id from t
$$;

create or replace function my_visible() returns setof uuid
  language sql stable security definer set search_path = public as $$
  select subtree(my_party())
$$;

-- caller's root importer (walk up the tree)
create or replace function my_importer() returns uuid
  language sql stable security definer set search_path = public as $$
  with recursive up as (
    select id, parent_id from parties where auth_uid = auth.uid()
    union all
    select p.id, p.parent_id from parties p join up on p.id = up.parent_id
  ) select id from up where parent_id is null limit 1
$$;

-- ---------- dealer-facing pricing & availability ----------
-- per-dealer net price; the importer's landing cost never leaves the DB, only net_rate
create or replace function my_prices() returns table(sku text, net_rate int)
  language sql stable security definer set search_path = public as $$
  select cc.sku,
    round(cc.dealer_rate * (1 + coalesce(p.margin_pct, rm.margin_pct, 20)/100.0))::int
  from catalog_cost cc
  join parties p on p.auth_uid = auth.uid()
  left join role_margins rm on rm.role = p.role
  where cc.dealer_rate is not null
$$;

-- availability the importer publishes to its dealers: in/out + the actual quantity on hand
create or replace function importer_availability() returns table(sku text, in_stock boolean, qty int)
  language sql stable security definer set search_path = public as $$
  select c.sku, coalesce(cs.qty,0) > 0, coalesce(cs.qty,0)
  from catalog c
  left join current_stock cs on cs.sku = c.sku and cs.party_id = my_importer()
$$;

-- ---------- ledger writes: billing = stock transfer ----------
create or replace function transfer(p_to uuid, p_sku text, p_qty int, p_pi text default null, p_note text default null)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_from uuid; v_avail int; v_id bigint;
begin
  v_from := my_party();
  if v_from is null then raise exception 'no party linked to this login'; end if;
  if p_qty is null or p_qty <= 0 then raise exception 'qty must be a positive integer'; end if;
  if p_to = v_from then raise exception 'from and to must differ'; end if;
  if not exists (select 1 from subtree(v_from) s where s = p_to) then
    raise exception 'can only ship into your own network';
  end if;
  select coalesce(qty,0) into v_avail from current_stock where party_id = v_from and sku = p_sku;
  if coalesce(v_avail,0) < p_qty then raise exception 'insufficient stock at source (have %, need %)', coalesce(v_avail,0), p_qty; end if;
  insert into movements(from_party, to_party, sku, qty, pi_number, note)
    values (v_from, p_to, p_sku, p_qty, p_pi, p_note) returning id into v_id;
  return v_id;
end $$;

create or replace function open_stock(p_sku text, p_qty int, p_note text default 'opening')
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_id bigint;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  if not exists (select 1 from parties where id = v_me and parent_id is null) then
    raise exception 'only the importer may add external stock';
  end if;
  if p_qty is null or p_qty <= 0 then raise exception 'qty must be a positive integer'; end if;
  insert into movements(from_party, to_party, sku, qty, note)
    values (null, v_me, p_sku, p_qty, p_note) returning id into v_id;
  return v_id;
end $$;

-- ---------- dealer orders (replaces Netlify Forms) ----------
create table if not exists orders (
  id             bigint generated always as identity primary key,
  dealer_party   uuid not null references parties(id),
  importer_party uuid references parties(id),
  pi_number      text,
  subtotal numeric, gst numeric, grand numeric,
  status         text not null default 'placed',
  created_at     timestamptz not null default now()
);
create table if not exists order_lines (
  order_id bigint not null references orders(id) on delete cascade,
  sku      text not null references catalog(sku),
  qty      int not null check (qty > 0),
  rate     int, amount int
);
create index if not exists order_lines_order_idx on order_lines(order_id);

-- a dealer places its PI as an order under its importer. Not a stock move; the
-- importer bills via transfer() to actually move stock ("stock decrements on billing").
create or replace function place_order(p_pi text, p_subtotal numeric, p_gst numeric, p_grand numeric, p_lines jsonb)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_dealer uuid; v_imp uuid; v_id bigint;
begin
  v_dealer := my_party();
  if v_dealer is null then raise exception 'no party linked to this login'; end if;
  v_imp := my_importer();
  insert into orders(dealer_party, importer_party, pi_number, subtotal, gst, grand)
    values (v_dealer, v_imp, p_pi, p_subtotal, p_gst, p_grand) returning id into v_id;
  insert into order_lines(order_id, sku, qty, rate, amount)
    select v_id, (l->>'sku'), (l->>'qty')::int, (l->>'rate')::int, (l->>'amount')::int
    from jsonb_array_elements(p_lines) l;
  return v_id;
end $$;

-- importer fulfils a request: bills exactly the requested lines (transfers stock
-- importer -> dealer, all-or-nothing) and marks the order billed. Closes the loop.
create or replace function fulfill_order(p_order_id bigint)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_ord orders; v_line record; v_avail int;
begin
  v_me := my_party();
  if v_me is null or not exists (select 1 from parties where id = v_me and parent_id is null) then
    raise exception 'only the importer may bill orders'; end if;
  select * into v_ord from orders where id = p_order_id;
  if v_ord.id is null then raise exception 'no such order'; end if;
  if v_ord.importer_party <> v_me then raise exception 'not your order'; end if;
  if v_ord.status = 'billed' then raise exception 'order already billed'; end if;
  for v_line in select sku, qty from order_lines where order_id = p_order_id loop
    select coalesce(qty,0) into v_avail from current_stock where party_id = v_me and sku = v_line.sku;
    if coalesce(v_avail,0) < v_line.qty then
      raise exception 'not enough stock for % (have %, need %)', v_line.sku, coalesce(v_avail,0), v_line.qty; end if;
    insert into movements(from_party, to_party, sku, qty, pi_number, note)
      values (v_me, v_ord.dealer_party, v_line.sku, v_line.qty, v_ord.pi_number, 'order ' || p_order_id);
  end loop;
  update orders set status = 'billed' where id = p_order_id;
end $$;

create or replace function reject_order(p_order_id bigint)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid;
begin
  v_me := my_party();
  if v_me is null or not exists (select 1 from parties where id = v_me and parent_id is null) then
    raise exception 'only the importer may reject orders'; end if;
  update orders set status = 'rejected' where id = p_order_id and importer_party = v_me and status = 'placed';
end $$;

-- ---------- RLS = the visibility tree ----------
alter table parties      enable row level security;
alter table movements    enable row level security;
alter table catalog      enable row level security;
alter table catalog_cost enable row level security;
alter table orders       enable row level security;
alter table order_lines  enable row level security;

drop policy if exists parties_read on parties;
create policy parties_read on parties for select to authenticated
  using (id in (select my_visible()));

drop policy if exists movements_read on movements;
create policy movements_read on movements for select to authenticated
  using (to_party in (select my_visible()) or from_party in (select my_visible()));

-- catalog names/structure are shared reference data
drop policy if exists catalog_read on catalog;
create policy catalog_read on catalog for select to authenticated using (true);

-- landing cost is importer-only
drop policy if exists catalog_cost_importer on catalog_cost;
create policy catalog_cost_importer on catalog_cost for select to authenticated
  using (exists (select 1 from parties where auth_uid = auth.uid() and parent_id is null));

-- dealer sees its own orders; the importer up the tree sees orders placed to it
drop policy if exists orders_read on orders;
create policy orders_read on orders for select to authenticated
  using (dealer_party in (select my_visible()) or importer_party in (select my_visible()));
drop policy if exists order_lines_read on order_lines;
create policy order_lines_read on order_lines for select to authenticated
  using (order_id in (select id from orders));

-- No insert/update/delete policies on movements/orders: all writes go through the
-- SECURITY DEFINER functions (transfer/open_stock/place_order). Balances can't be forged.

-- ---------- self-service dealer registration (importer-approved) ----------
-- The dealer signs up in the app (types their OWN password) and records their business
-- details; the importer approves in ledger.html, which creates their party + links the login.
-- Requires Supabase Auth "Confirm email" OFF so sign-up returns a session immediately.
create table if not exists signup_requests (
  id             bigint generated always as identity primary key,
  auth_uid       uuid not null unique references auth.users(id),
  email          text,
  business_name  text,
  phone          text,
  requested_role text not null default 'dealer',
  status         text not null default 'pending',   -- pending | approved | rejected
  created_at     timestamptz not null default now()
);
alter table signup_requests enable row level security;
drop policy if exists signup_read on signup_requests;
create policy signup_read on signup_requests for select to authenticated
  using (auth_uid = auth.uid()
         or exists (select 1 from parties where auth_uid = auth.uid() and parent_id is null));

create or replace function request_access(p_business text, p_phone text, p_role text default 'dealer')
  returns text language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'must be signed in'; end if;
  if exists (select 1 from parties where auth_uid = auth.uid()) then return 'already_active'; end if;
  insert into signup_requests(auth_uid, email, business_name, phone, requested_role)
    values (auth.uid(), (select email from auth.users where id = auth.uid()), p_business, p_phone,
            case when p_role in ('dealer','distributor','shopkeeper') then p_role else 'dealer' end)
    on conflict (auth_uid) do update
      set business_name = excluded.business_name, phone = excluded.phone,
          requested_role = excluded.requested_role, status = 'pending';
  return 'pending';
end $$;

create or replace function my_status() returns text
  language sql stable security definer set search_path = public as $$
  select case
    when exists (select 1 from parties where auth_uid = auth.uid()) then 'active'
    else coalesce((select status from signup_requests where auth_uid = auth.uid()), 'none')
  end
$$;

create or replace function approve_signup(p_id bigint, p_margin numeric default null)
  returns uuid language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_req signup_requests; v_party uuid;
begin
  v_me := my_party();
  if v_me is null or not exists (select 1 from parties where id = v_me and parent_id is null) then
    raise exception 'only the importer may approve'; end if;
  select * into v_req from signup_requests where id = p_id and status = 'pending';
  if v_req.id is null then raise exception 'no such pending request'; end if;
  insert into parties(name, role, parent_id, margin_pct, auth_uid)
    values (coalesce(nullif(v_req.business_name,''), v_req.email), v_req.requested_role, v_me, p_margin, v_req.auth_uid)
    returning id into v_party;
  update signup_requests set status = 'approved' where id = p_id;
  return v_party;
end $$;

create or replace function reject_signup(p_id bigint)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid;
begin
  v_me := my_party();
  if v_me is null or not exists (select 1 from parties where id = v_me and parent_id is null) then
    raise exception 'only the importer may reject'; end if;
  update signup_requests set status = 'rejected' where id = p_id and status = 'pending';
end $$;

-- ===================================================================
-- ROUND 2 additions (multi-tier onboarding, retail storefront).
-- create-or-replace overrides the earlier definitions when run top-to-bottom,
-- so running this file start-to-finish yields the final production state.
-- ===================================================================

-- --- multi-tier: orders route to the DIRECT supplier; any supplier fulfils ---
create or replace function place_order(p_pi text, p_subtotal numeric, p_gst numeric, p_grand numeric, p_lines jsonb)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_dealer uuid; v_sup uuid; v_id bigint;
begin
  v_dealer := my_party();
  if v_dealer is null then raise exception 'no party linked to this login'; end if;
  v_sup := (select parent_id from parties where id = v_dealer);
  insert into orders(dealer_party, importer_party, pi_number, subtotal, gst, grand)
    values (v_dealer, v_sup, p_pi, p_subtotal, p_gst, p_grand) returning id into v_id;
  insert into order_lines(order_id, sku, qty, rate, amount)
    select v_id, (l->>'sku'), (l->>'qty')::int, (l->>'rate')::int, (l->>'amount')::int
    from jsonb_array_elements(p_lines) l;
  return v_id;
end $$;

create or replace function fulfill_order(p_order_id bigint)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_ord orders; v_line record; v_avail int;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  select * into v_ord from orders where id = p_order_id;
  if v_ord.id is null then raise exception 'no such order'; end if;
  if v_ord.importer_party <> v_me then raise exception 'this request was not placed to you'; end if;
  if v_ord.status = 'billed' then raise exception 'order already billed'; end if;
  for v_line in select sku, qty from order_lines where order_id = p_order_id loop
    select coalesce(qty,0) into v_avail from current_stock where party_id = v_me and sku = v_line.sku;
    if coalesce(v_avail,0) < v_line.qty then
      raise exception 'not enough stock for % (have %, need %)', v_line.sku, coalesce(v_avail,0), v_line.qty; end if;
    insert into movements(from_party, to_party, sku, qty, pi_number, note)
      values (v_me, v_ord.dealer_party, v_line.sku, v_line.qty, v_ord.pi_number, 'order ' || p_order_id);
  end loop;
  update orders set status = 'billed' where id = p_order_id;
end $$;

-- a buyer sees their DIRECT supplier's stock (dealer sees importer; shopkeeper sees dealer)
-- a party sees its SUPPLIER's availability (its parent's stock). The root importer
-- has no parent, so coalesce(parent_id, id) falls back to their own party — they see
-- the warehouse they actually hold. Non-root parties are unchanged.
create or replace function importer_availability() returns table(sku text, in_stock boolean, qty int)
  language sql stable security definer set search_path = public as $$
  select c.sku, coalesce(cs.qty,0) > 0, coalesce(cs.qty,0)
  from catalog c
  left join current_stock cs on cs.sku = c.sku
    and cs.party_id = (select coalesce(parent_id, id) from parties where auth_uid = auth.uid())
$$;

-- --- onboarding: any party invites a party under them; invitee sets own password ---
alter table parties add column if not exists phone text;
alter table parties add column if not exists pending_email text;

create or replace function link_invited_party() returns trigger
  language plpgsql security definer set search_path = public as $$
begin
  update parties set auth_uid = NEW.id, pending_email = null
  where auth_uid is null and pending_email is not null and lower(pending_email) = lower(NEW.email);
  return NEW;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function link_invited_party();

create or replace function add_downstream(p_name text, p_role text, p_email text,
                                          p_phone text default null, p_city text default null, p_margin numeric default null)
  returns uuid language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_id uuid; v_ok boolean;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  v_ok := case (select role from parties where id = v_me)
            when 'importer'    then p_role in ('distributor','dealer','shopkeeper')
            when 'distributor' then p_role in ('dealer','shopkeeper')
            when 'dealer'      then p_role in ('shopkeeper')
            else false end;
  if not v_ok then raise exception 'your role cannot create a %', p_role; end if;
  if exists (select 1 from parties where lower(pending_email) = lower(p_email) or auth_uid in
             (select id from auth.users where lower(email) = lower(p_email))) then
    raise exception 'a party with that email already exists'; end if;
  insert into parties(name, role, parent_id, phone, city, margin_pct, pending_email)
    values (p_name, p_role, v_me, p_phone, p_city, p_margin, lower(p_email)) returning id into v_id;
  return v_id;
end $$;

-- --- retail storefront: a party shares a link; end users order at MRP (3x) ---
create or replace function enduser_prices() returns table(sku text, mrp int)
  language sql stable security definer set search_path = public as $$
  select sku, round(dealer_rate * 3)::int from catalog_cost where dealer_rate is not null
$$;
create or replace function supplier_availability(p_supplier uuid) returns table(sku text, in_stock boolean)
  language sql stable security definer set search_path = public as $$
  select c.sku, coalesce(cs.qty,0) > 0
  from catalog c left join current_stock cs on cs.sku = c.sku and cs.party_id = p_supplier
$$;
create or replace function supplier_name(p_supplier uuid) returns text
  language sql stable security definer set search_path = public as $$
  select name from parties where id = p_supplier
$$;

create table if not exists enduser_orders (
  id             bigint generated always as identity primary key,
  supplier_party uuid not null references parties(id),
  customer_name  text, customer_phone text,
  pi_number      text, subtotal numeric, grand numeric,
  status         text not null default 'placed',
  created_at     timestamptz not null default now()
);
create table if not exists enduser_order_lines (
  order_id bigint not null references enduser_orders(id) on delete cascade,
  sku text not null references catalog(sku), qty int not null check (qty>0), rate int, amount int
);
create index if not exists enduser_order_lines_idx on enduser_order_lines(order_id);
alter table enduser_orders enable row level security;
alter table enduser_order_lines enable row level security;
drop policy if exists enduser_orders_read on enduser_orders;
create policy enduser_orders_read on enduser_orders for select to authenticated
  using (supplier_party in (select my_visible()));
drop policy if exists enduser_order_lines_read on enduser_order_lines;
create policy enduser_order_lines_read on enduser_order_lines for select to authenticated
  using (order_id in (select id from enduser_orders));

create or replace function place_enduser_order(p_supplier uuid, p_name text, p_phone text, p_lines jsonb)
  returns text language plpgsql security definer set search_path = public as $$
declare v_id bigint; v_sub numeric := 0; v_line jsonb; v_rate int; v_qty int; v_pi text;
begin
  if not exists (select 1 from parties where id = p_supplier) then raise exception 'unknown supplier'; end if;
  v_pi := 'EU-' || to_char(now(),'YYYYMMDD-HH24MISS');
  insert into enduser_orders(supplier_party, customer_name, customer_phone, pi_number, subtotal, grand)
    values (p_supplier, p_name, p_phone, v_pi, 0, 0) returning id into v_id;
  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := (v_line->>'qty')::int;
    select round(dealer_rate*3)::int into v_rate from catalog_cost where sku = (v_line->>'sku');
    if v_rate is null or v_qty is null or v_qty <= 0 then continue; end if;
    insert into enduser_order_lines(order_id, sku, qty, rate, amount)
      values (v_id, (v_line->>'sku'), v_qty, v_rate, v_rate*v_qty);
    v_sub := v_sub + v_rate*v_qty;
  end loop;
  update enduser_orders set subtotal = v_sub, grand = v_sub where id = v_id;
  return v_pi;
end $$;

grant execute on function enduser_prices() to anon;
grant execute on function supplier_availability(uuid) to anon;
grant execute on function supplier_name(uuid) to anon;
grant execute on function place_enduser_order(uuid, text, text, jsonb) to anon;

-- ===================================================================
-- ROUND 3: web push (phone alerts). The webhook secret below is REDACTED —
-- the deployed trigger uses the real secret (kept in Supabase, not this repo).
-- ===================================================================
create table if not exists push_subscriptions (
  id bigint generated always as identity primary key,
  party_id uuid not null references parties(id),
  endpoint text not null unique, p256dh text not null, auth text not null,
  created_at timestamptz not null default now()
);
alter table push_subscriptions enable row level security;
drop policy if exists push_own on push_subscriptions;
create policy push_own on push_subscriptions for all to authenticated
  using (party_id = my_party()) with check (party_id = my_party());

create or replace function save_push_subscription(p_endpoint text, p_p256dh text, p_auth text)
  returns void language plpgsql security definer set search_path = public as $$
begin
  if my_party() is null then raise exception 'no party linked to this login'; end if;
  insert into push_subscriptions(party_id, endpoint, p256dh, auth)
    values (my_party(), p_endpoint, p_p256dh, p_auth)
    on conflict (endpoint) do update set party_id = excluded.party_id, p256dh = excluded.p256dh, auth = excluded.auth;
end $$;

create extension if not exists pg_net;
-- resilient: a push failure never blocks the order insert
create or replace function notify_new_order() returns trigger
  language plpgsql security definer set search_path = public, net as $$
begin
  begin
    perform net.http_post(
      url := 'https://hzpvdeepyejhkshzrfsm.supabase.co/functions/v1/notify',
      headers := jsonb_build_object('Content-Type','application/json','x-webhook-secret','REDACTED_SET_YOUR_OWN'),
      body := jsonb_build_object('table', TG_TABLE_NAME, 'record', row_to_json(NEW))
    );
  exception when others then null;
  end;
  return NEW;
end $$;
drop trigger if exists orders_notify on orders;
create trigger orders_notify after insert on orders for each row execute function notify_new_order();
drop trigger if exists euorders_notify on enduser_orders;
create trigger euorders_notify after insert on enduser_orders for each row execute function notify_new_order();
alter publication supabase_realtime add table orders;
alter publication supabase_realtime add table enduser_orders;

-- ===================================================================
-- ROUND 4: race-safety on concurrent billing + server-computed order pricing.
-- create-or-replace overrides the earlier definitions when run top-to-bottom.
-- ===================================================================

-- transfer(): lock the SOURCE party (stock is leaving them) before reading/checking
-- its balance, so two concurrent transfers/fulfils from the same party can't both
-- pass the "enough stock" check against a balance that's about to change under them.
-- ponytail: one advisory lock per party (hashtext collisions are astronomically rare
-- for this party count) — upgrade to a real per-row lock if that ever matters.
create or replace function transfer(p_to uuid, p_sku text, p_qty int, p_pi text default null, p_note text default null)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_from uuid; v_avail int; v_id bigint;
begin
  v_from := my_party();
  if v_from is null then raise exception 'no party linked to this login'; end if;
  if p_qty is null or p_qty <= 0 then raise exception 'qty must be a positive integer'; end if;
  if p_to = v_from then raise exception 'from and to must differ'; end if;
  if not exists (select 1 from subtree(v_from) s where s = p_to) then
    raise exception 'can only ship into your own network';
  end if;
  perform pg_advisory_xact_lock(hashtext(v_from::text));
  select coalesce(qty,0) into v_avail from current_stock where party_id = v_from and sku = p_sku;
  if coalesce(v_avail,0) < p_qty then raise exception 'insufficient stock at source (have %, need %)', coalesce(v_avail,0), p_qty; end if;
  insert into movements(from_party, to_party, sku, qty, pi_number, note)
    values (v_from, p_to, p_sku, p_qty, p_pi, p_note) returning id into v_id;
  return v_id;
end $$;

-- fulfill_order(): same race guard — lock the billing party before checking stock
-- for each requested line.
create or replace function fulfill_order(p_order_id bigint)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_ord orders; v_line record; v_avail int;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  select * into v_ord from orders where id = p_order_id;
  if v_ord.id is null then raise exception 'no such order'; end if;
  if v_ord.importer_party <> v_me then raise exception 'this request was not placed to you'; end if;
  if v_ord.status = 'billed' then raise exception 'order already billed'; end if;
  perform pg_advisory_xact_lock(hashtext(v_me::text));
  for v_line in select sku, qty from order_lines where order_id = p_order_id loop
    select coalesce(qty,0) into v_avail from current_stock where party_id = v_me and sku = v_line.sku;
    if coalesce(v_avail,0) < v_line.qty then
      raise exception 'not enough stock for % (have %, need %)', v_line.sku, coalesce(v_avail,0), v_line.qty; end if;
    insert into movements(from_party, to_party, sku, qty, pi_number, note)
      values (v_me, v_ord.dealer_party, v_line.sku, v_line.qty, v_ord.pi_number, 'order ' || p_order_id);
  end loop;
  update orders set status = 'billed' where id = p_order_id;
end $$;

-- place_order(): the client-submitted subtotal/gst/grand/rate/amount are NEVER trusted —
-- the server recomputes each line's rate from catalog_cost + the buyer's own margin, the
-- same formula my_prices() uses, so a tampered client payload can't under-bill an order.
-- qty is capped per line; a party with no parent (the importer itself) can't self-order.
create or replace function place_order(p_pi text, p_subtotal numeric, p_gst numeric, p_grand numeric, p_lines jsonb)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_dealer uuid; v_sup uuid; v_id bigint; v_line jsonb; v_qty int; v_rate int; v_sub numeric := 0;
begin
  v_dealer := my_party();
  if v_dealer is null then raise exception 'no party linked to this login'; end if;
  v_sup := (select parent_id from parties where id = v_dealer);
  if v_sup is null then raise exception 'the importer cannot place purchase requests'; end if;
  insert into orders(dealer_party, importer_party, pi_number, subtotal, gst, grand)
    values (v_dealer, v_sup, p_pi, 0, 0, 0) returning id into v_id;
  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := least(greatest(coalesce((v_line->>'qty')::int, 0), 0), 500);
    select round(cc.dealer_rate * (1 + coalesce(p.margin_pct, rm.margin_pct, 20)/100.0))::int
      into v_rate
      from catalog_cost cc
      join parties p on p.id = v_dealer
      left join role_margins rm on rm.role = p.role
      where cc.sku = (v_line->>'sku') and cc.dealer_rate is not null;
    if v_rate is null or v_qty <= 0 then continue; end if;
    insert into order_lines(order_id, sku, qty, rate, amount)
      values (v_id, (v_line->>'sku'), v_qty, v_rate, v_rate * v_qty);
    v_sub := v_sub + v_rate * v_qty;
  end loop;
  update orders set subtotal = v_sub, gst = round(v_sub * 0.05), grand = v_sub + round(v_sub * 0.05) where id = v_id;
  return v_id;
end $$;

-- place_enduser_order(): cap qty per line and cap the number of lines processed, so an
-- unauthenticated retail link can't be used to force an unbounded insert.
create or replace function place_enduser_order(p_supplier uuid, p_name text, p_phone text, p_lines jsonb)
  returns text language plpgsql security definer set search_path = public as $$
declare v_id bigint; v_sub numeric := 0; v_line jsonb; v_rate int; v_qty int; v_pi text;
begin
  if not exists (select 1 from parties where id = p_supplier) then raise exception 'unknown supplier'; end if;
  v_pi := 'EU-' || to_char(now(),'YYYYMMDD-HH24MISS');
  insert into enduser_orders(supplier_party, customer_name, customer_phone, pi_number, subtotal, grand)
    values (p_supplier, p_name, p_phone, v_pi, 0, 0) returning id into v_id;
  for v_line in select elem from jsonb_array_elements(p_lines) with ordinality as t(elem, ord) where ord <= 100 loop
    v_qty := least(greatest(coalesce((v_line->>'qty')::int, 0), 0), 500);
    select round(dealer_rate*3)::int into v_rate from catalog_cost where sku = (v_line->>'sku');
    if v_rate is null or v_qty <= 0 then continue; end if;
    insert into enduser_order_lines(order_id, sku, qty, rate, amount)
      values (v_id, (v_line->>'sku'), v_qty, v_rate, v_rate*v_qty);
    v_sub := v_sub + v_rate*v_qty;
  end loop;
  update enduser_orders set subtotal = v_sub, grand = v_sub where id = v_id;
  return v_pi;
end $$;

-- ROUND 5 — demand ledger (out-of-stock requests).
-- Separate from billable orders: a demand row records that someone asked for a part
-- their supplier didn't have, so the supplier can restock and close the loop. It never
-- moves stock or money on its own — resolve_demand() only flips its status.
create table if not exists demand_requests (
  id               bigint generated always as identity primary key,
  created_at       timestamptz not null default now(),
  sku              text not null references catalog(sku),
  qty              int not null,
  note             text,
  status           text not null default 'open' check (status in ('open','sourced')),
  source           text not null check (source in ('dealer','enduser')),
  supplier_party   uuid not null references parties(id),   -- who the demand was raised to
  requester_party  uuid references parties(id),            -- set when source = 'dealer'
  requester_name   text,                                    -- set when source = 'enduser' (retail, no login)
  requester_phone  text
);
alter table demand_requests enable row level security;
-- visible to the supplier the demand was raised to, or the dealer/shopkeeper who raised it
-- (my_visible() = me + my descendants, same tree helper used elsewhere for RLS)
create policy demand_read on demand_requests for select using (
  supplier_party in (select my_visible()) or requester_party in (select my_visible())
);
-- no insert/update policy: all writes go through the SECURITY DEFINER functions below

create or replace view demand_feed with (security_invoker = true) as
  select d.id, d.created_at, d.sku, c.product_code, c.particular, d.qty, d.note, d.status, d.source,
         sp.name as supplier_party, sp.name as supplier_name, d.requester_party,
         coalesce(rp.name, d.requester_name) as requester_name, d.requester_phone
  from demand_requests d
  join catalog c on c.sku = d.sku
  join parties sp on sp.id = d.supplier_party
  left join parties rp on rp.id = d.requester_party;

-- record_demand(): logged-in dealer/shopkeeper requesting a part from their DIRECT supplier
-- (their parent party). qty is clamped, same guard as the other order-entry RPCs.
create or replace function record_demand(p_sku text, p_qty int, p_note text)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_sup uuid; v_id bigint;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  v_sup := (select parent_id from parties where id = v_me);
  if v_sup is null then raise exception 'the importer has no supplier to request from'; end if;
  insert into demand_requests(sku, qty, note, source, supplier_party, requester_party)
    values (p_sku, least(greatest(coalesce(p_qty,0),1),500), p_note, 'dealer', v_sup, v_me)
    returning id into v_id;
  return v_id;
end $$;

-- record_enduser_demand(): anonymous retail request via a storefront link; recorded against
-- the storefront's supplier party. No auth required, same trust model as place_enduser_order().
create or replace function record_enduser_demand(p_supplier uuid, p_name text, p_phone text, p_sku text, p_qty int)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if not exists (select 1 from parties where id = p_supplier) then raise exception 'unknown supplier'; end if;
  insert into demand_requests(sku, qty, source, supplier_party, requester_name, requester_phone)
    values (p_sku, least(greatest(coalesce(p_qty,0),1),500), 'enduser', p_supplier, p_name, p_phone)
    returning id into v_id;
  return v_id;
end $$;

-- resolve_demand(): supplier marks a demand row sourced once restocked. RLS on demand_requests
-- already scopes selects to visible rows; this just checks the caller is the addressed supplier.
create or replace function resolve_demand(p_id bigint, p_status text)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid;
begin
  v_me := my_party();
  if not exists (select 1 from demand_requests where id = p_id and supplier_party = v_me) then
    raise exception 'not your demand request'; end if;
  update demand_requests set status = p_status where id = p_id;
end $$;

grant execute on function record_demand(text, int, text) to authenticated;
grant execute on function record_enduser_demand(uuid, text, text, text, int) to anon, authenticated;
grant execute on function resolve_demand(bigint, text) to authenticated;

-- ===================================================================
-- ROUND 6: forward orders upstream (drop-ship), amend qty before billing,
-- bill attachment. From the 26-07-24 call with the Source India prospect:
--  * an order landing at a party with no stock gets forwarded to THEIR
--    supplier as a purchase request carrying the end customer's ship-to;
--    once the upstream bills them, stock increments and the original order
--    is billable with the existing button — double-entry stays exact and
--    the downstream buyer never learns the upstream source.
--  * "50 नहीं, 40 दे पाऊंगा": supplier edits quantities on an incoming
--    request instead of reject → re-place.
--  * the accountant's bill travels with the order instead of WhatsApp.
-- ===================================================================

alter table orders add column if not exists ship_to         text;
alter table orders add column if not exists source_kind     text check (source_kind in ('dealer','enduser'));
alter table orders add column if not exists source_order_id bigint;
alter table orders add column if not exists bill_url        text;
alter table orders add column if not exists amended         boolean not null default false;

-- forward an incoming order upstream as my own purchase request.
-- kind 'dealer'  = a downstream party's order placed to me (orders)
-- kind 'enduser' = a retail order on my storefront (enduser_orders)
-- p_lines: optional {"L0001": 6, ...} the dealer types on the card to override how
-- much of each SKU to ask the importer for (0 drops it). When null, the qty defaults
-- to the deficit (asked minus what I already hold). Overrides only touch SKUs that
-- exist on the source order — no new SKUs can be injected.
drop function if exists forward_order(text, bigint);
create or replace function forward_order(p_kind text, p_order_id bigint, p_lines jsonb default null)
  returns bigint language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_sup uuid; v_id bigint; v_ship text; v_pi text; v_rate int; v_sub numeric := 0; v_line record; v_need int; v_have int;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  v_sup := (select parent_id from parties where id = v_me);
  if v_sup is null then raise exception 'you have no upstream supplier to forward to'; end if;
  if p_kind not in ('dealer','enduser') then raise exception 'bad kind'; end if;
  if exists (select 1 from orders where source_kind = p_kind and source_order_id = p_order_id) then
    raise exception 'already forwarded'; end if;

  -- validate the source order was placed to me, and grab its PI for a reference number.
  -- ship_to is MY OWN name — the importer bills and ships to me, and never learns the
  -- downstream customer's identity. I re-bill the customer myself.
  if p_kind = 'dealer' then
    select 'FWD-' || coalesce(o.pi_number, o.id::text) into v_pi
      from orders o
      where o.id = p_order_id and o.importer_party = v_me and o.status = 'placed';
  else
    select 'FWD-' || coalesce(pi_number, id::text) into v_pi
      from enduser_orders where id = p_order_id and supplier_party = v_me;
  end if;
  if v_pi is null then raise exception 'no such open order placed to you'; end if;
  select 'Ship to: ' || name || coalesce(', ' || city, '') || coalesce(' ' || pin, '')
    into v_ship from parties where id = v_me;

  insert into orders(dealer_party, importer_party, pi_number, subtotal, gst, grand,
                     ship_to, source_kind, source_order_id)
    values (v_me, v_sup, v_pi, 0, 0, 0, v_ship, p_kind, p_order_id) returning id into v_id;

  -- forward only the DEFICIT: asked qty minus what I already hold, at MY buy rate
  -- (cost + my margin — same formula as place_order). Lines I can fully cover are skipped.
  for v_line in
    select l.sku, l.qty from order_lines l where p_kind = 'dealer' and l.order_id = p_order_id
    union all
    select l.sku, l.qty from enduser_order_lines l where p_kind = 'enduser' and l.order_id = p_order_id
  loop
    if p_lines is null then
      select coalesce(qty,0) into v_have from current_stock where party_id = v_me and sku = v_line.sku;
      v_need := v_line.qty - coalesce(v_have, 0);
    else
      v_need := least(greatest(coalesce((p_lines->>v_line.sku)::int, 0), 0), 500);
    end if;
    if v_need <= 0 then continue; end if;
    select round(cc.dealer_rate * (1 + coalesce(p.margin_pct, rm.margin_pct, 20)/100.0))::int
      into v_rate
      from catalog_cost cc
      join parties p on p.id = v_me
      left join role_margins rm on rm.role = p.role
      where cc.sku = v_line.sku and cc.dealer_rate is not null;
    if v_rate is null then continue; end if;
    insert into order_lines(order_id, sku, qty, rate, amount)
      values (v_id, v_line.sku, v_need, v_rate, v_rate * v_need);
    v_sub := v_sub + v_rate * v_need;
  end loop;
  if v_sub = 0 then
    delete from orders where id = v_id;
    raise exception 'nothing to forward — you already hold enough stock for this order';
  end if;
  update orders set subtotal = v_sub, gst = round(v_sub * 0.05), grand = v_sub + round(v_sub * 0.05)
    where id = v_id;
  return v_id;
end $$;

-- supplier adjusts quantities on an incoming request before billing.
-- p_lines = [{"sku":"L0001","qty":40}, ...]; qty 0 drops the line; SKUs not
-- mentioned keep their qty. Rates never change here (server-set at placement).
create or replace function amend_order_qty(p_order_id bigint, p_lines jsonb)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid; v_ord orders; v_line jsonb; v_qty int; v_sub numeric;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  select * into v_ord from orders where id = p_order_id;
  if v_ord.id is null then raise exception 'no such order'; end if;
  if v_ord.importer_party <> v_me then raise exception 'this request was not placed to you'; end if;
  if v_ord.status <> 'placed' then raise exception 'only open requests can be adjusted'; end if;
  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_qty := least(greatest(coalesce((v_line->>'qty')::int, 0), 0), 500);
    if v_qty = 0 then
      delete from order_lines where order_id = p_order_id and sku = (v_line->>'sku');
    else
      update order_lines set qty = v_qty, amount = rate * v_qty
        where order_id = p_order_id and sku = (v_line->>'sku');
    end if;
  end loop;
  select coalesce(sum(amount), 0) into v_sub from order_lines where order_id = p_order_id;
  if v_sub = 0 then raise exception 'cannot drop every line — reject the request instead'; end if;
  update orders set subtotal = v_sub, gst = round(v_sub * 0.05),
                    grand = v_sub + round(v_sub * 0.05), amended = true
    where id = p_order_id;
end $$;

-- either party of an order attaches the bill (a storage URL). Overwrites allowed:
-- the newest bill is the truth.
create or replace function attach_bill(p_order_id bigint, p_url text)
  returns void language plpgsql security definer set search_path = public as $$
declare v_me uuid;
begin
  v_me := my_party();
  if v_me is null then raise exception 'no party linked to this login'; end if;
  if p_url is null or p_url not like 'https://%' or length(p_url) > 500 then
    raise exception 'bad bill url'; end if;
  update orders set bill_url = p_url
    where id = p_order_id and (importer_party = v_me or dealer_party = v_me);
  if not found then raise exception 'not your order'; end if;
end $$;

grant execute on function forward_order(text, bigint, jsonb) to authenticated;
grant execute on function amend_order_qty(bigint, jsonb) to authenticated;
grant execute on function attach_bill(bigint, text) to authenticated;

-- bills bucket: public-read (URLs are unguessable uuid paths), authenticated upload.
insert into storage.buckets (id, name, public) values ('bills','bills', true)
  on conflict (id) do nothing;
drop policy if exists bills_upload on storage.objects;
create policy bills_upload on storage.objects for insert to authenticated
  with check (bucket_id = 'bills');
